use std::path::Path;

use lofty::prelude::*;
use serde::Serialize;

use crate::error::Result;

/// Metadata scan results
#[derive(Debug, Clone, Default, Serialize)]
pub struct MetadataScanResult {
    pub tags: Vec<TagInfo>,
    pub suspicious_chunks: Vec<ChunkInfo>,
    pub anomalies: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TagInfo {
    pub tag_type: String,
    pub key: String,
    pub value: String,
    pub suspicious: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct ChunkInfo {
    pub description: String,
    pub offset: u64,
}

pub struct MetadataScanner;

impl MetadataScanner {
    pub fn scan(path: &Path) -> Result<MetadataScanResult> {
        let mut result = MetadataScanResult::default();

        if let Ok(tagged_file) = lofty::read_from_path(path) {
            for tag in tagged_file.tags() {
                let tag_type = format!("{:?}", tag.tag_type());
                for item in tag.items() {
                    let key = format!("{:?}", item.key());
                    let value = format!("{:?}", item.value());
                    let suspicious = is_suspicious_tag(&key, &value);
                    result.tags.push(TagInfo {
                        tag_type: tag_type.clone(),
                        key,
                        value,
                        suspicious,
                    });
                }
            }
        }

        // Binary scan for suspicious patterns
        if let Ok(data) = std::fs::read(path) {
            scan_binary_patterns(&data, &mut result);
        }

        Ok(result)
    }
}

fn is_suspicious_tag(key: &str, value: &str) -> bool {
    let key_lower = key.to_lowercase();
    let value_lower = value.to_lowercase();
    let suspicious_keys = [
        "unique",
        "fingerprint",
        "identifier",
        "tracking",
        "license",
        "isrc",
        "barcode",
        "upc",
        "ean",
        "catalog",
        "txxx",
    ];
    let suspicious_values = [
        "suno",
        "udio",
        "audiocraft",
        "musicgen",
        "stable audio",
        "ai-generated",
        "generated by",
    ];
    suspicious_keys.iter().any(|k| key_lower.contains(k))
        || suspicious_values.iter().any(|v| value_lower.contains(v))
}

fn scan_binary_patterns(data: &[u8], result: &mut MetadataScanResult) {
    let patterns: &[(&[u8], &str)] = &[
        (b"SUNO", "AI watermark marker"),
        (b"UDIO", "Udio AI marker"),
        (b"AudioCraft", "Meta AudioCraft marker"),
        (b"MusicGen", "MusicGen marker"),
        (b"Stable Audio", "Stable Audio marker"),
        (b"APETAGEX", "APE tag"),
        (b"ID3", "ID3 tag header"),
    ];

    for (pattern, description) in patterns {
        for (offset, window) in data.windows(pattern.len()).enumerate() {
            if window == *pattern {
                result.suspicious_chunks.push(ChunkInfo {
                    description: description.to_string(),
                    offset: offset as u64,
                });
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_suspicious_tag_keys() {
        assert!(is_suspicious_tag("UniqueFileID", "some-value"));
        assert!(is_suspicious_tag("TXXX:Fingerprint", "abc123"));
        assert!(is_suspicious_tag("ISRC", "US1234567890"));
        assert!(is_suspicious_tag("Tracking-ID", "xyz"));
    }

    #[test]
    fn test_suspicious_tag_values() {
        assert!(is_suspicious_tag("Comment", "Generated by Suno AI"));
        assert!(is_suspicious_tag("Encoder", "Udio v2"));
        assert!(is_suspicious_tag("Software", "AudioCraft toolkit"));
        assert!(is_suspicious_tag("Tool", "MusicGen model"));
    }

    #[test]
    fn test_non_suspicious_tags() {
        assert!(!is_suspicious_tag("Title", "My Song"));
        assert!(!is_suspicious_tag("Artist", "John Doe"));
        assert!(!is_suspicious_tag("Album", "Greatest Hits"));
        assert!(!is_suspicious_tag("Genre", "Rock"));
    }

    #[test]
    fn test_scan_binary_patterns_finds_markers() {
        let mut data = vec![0u8; 100];
        data[10..14].copy_from_slice(b"SUNO");
        data[50..54].copy_from_slice(b"UDIO");

        let mut result = MetadataScanResult::default();
        scan_binary_patterns(&data, &mut result);
        assert_eq!(result.suspicious_chunks.len(), 2);
        assert_eq!(result.suspicious_chunks[0].offset, 10);
        assert_eq!(result.suspicious_chunks[1].offset, 50);
    }

    #[test]
    fn test_scan_binary_patterns_clean_data() {
        let data = vec![0u8; 100];
        let mut result = MetadataScanResult::default();
        scan_binary_patterns(&data, &mut result);
        assert!(result.suspicious_chunks.is_empty());
    }

    #[test]
    fn test_scan_binary_id3_header() {
        let mut data = vec![0u8; 50];
        data[0..3].copy_from_slice(b"ID3");
        let mut result = MetadataScanResult::default();
        scan_binary_patterns(&data, &mut result);
        assert_eq!(result.suspicious_chunks.len(), 1);
        assert!(result.suspicious_chunks[0].description.contains("ID3"));
    }
}
