use std::path::Path;

use lofty::prelude::*;
use serde::Serialize;

use crate::error::Result;

/// Metadata scan results
#[derive(Debug, Clone, Default, Serialize)]
pub struct MetadataScanResult {
    pub tags: Vec<TagInfo>,
    pub suspicious_chunks: Vec<ChunkInfo>,
    pub anomalies: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TagInfo {
    pub tag_type: String,
    pub key: String,
    pub value: String,
    pub suspicious: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct ChunkInfo {
    pub description: String,
    pub offset: u64,
}

pub struct MetadataScanner;

impl MetadataScanner {
    pub fn scan(path: &Path) -> Result<MetadataScanResult> {
        let mut result = MetadataScanResult::default();

        if let Ok(tagged_file) = lofty::read_from_path(path) {
            for tag in tagged_file.tags() {
                let tag_type = format!("{:?}", tag.tag_type());
                for item in tag.items() {
                    let key = format!("{:?}", item.key());
                    let value = format!("{:?}", item.value());
                    let suspicious = is_suspicious_tag(&key, &value);
                    result.tags.push(TagInfo {
                        tag_type: tag_type.clone(),
                        key,
                        value,
                        suspicious,
                    });
                }
            }
        }

        // Binary scan for suspicious patterns
        if let Ok(data) = std::fs::read(path) {
            scan_binary_patterns(&data, &mut result);
        }

        Ok(result)
    }
}

fn is_suspicious_tag(key: &str, value: &str) -> bool {
    let key_lower = key.to_lowercase();
    let value_lower = value.to_lowercase();
    let suspicious_keys = [
        "unique",
        "fingerprint",
        "identifier",
        "tracking",
        "license",
        "isrc",
        "barcode",
        "upc",
        "ean",
        "catalog",
        "txxx",
    ];
    let suspicious_values = [
        "suno",
        "udio",
        "audiocraft",
        "musicgen",
        "stable audio",
        "ai-generated",
        "generated by",
    ];
    suspicious_keys.iter().any(|k| key_lower.contains(k))
        || suspicious_values.iter().any(|v| value_lower.contains(v))
}

fn scan_binary_patterns(data: &[u8], result: &mut MetadataScanResult) {
    let patterns: &[(&[u8], &str)] = &[
        (b"SUNO", "AI watermark marker"),
        (b"UDIO", "Udio AI marker"),
        (b"AudioCraft", "Meta AudioCraft marker"),
        (b"MusicGen", "MusicGen marker"),
        (b"Stable Audio", "Stable Audio marker"),
        (b"APETAGEX", "APE tag"),
        (b"ID3", "ID3 tag header"),
    ];

    for (pattern, description) in patterns {
        for (offset, window) in data.windows(pattern.len()).enumerate() {
            if window == *pattern {
                result.suspicious_chunks.push(ChunkInfo {
                    description: description.to_string(),
                    offset: offset as u64,
                });
            }
        }
    }
}
